'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const vm = require('node:vm')
const { parseAllowlist, parseSourceKey, parsePlaylistInput, issueConfirmation, verifyConfirmation, resolveAllowlistedSource, playlistSnapshot, metadataDigest, parseTitle, modeledCost, isApprovable } = require('./trusted-playlists.cjs')

test('playlist URL parser accepts canonical hosts and rejects SSRF or malformed input', () => {
  assert.equal(parsePlaylistInput('PL123456789012345678901234').playlistId, 'PL123456789012345678901234')
  assert.equal(parsePlaylistInput('https://www.youtube.com/playlist?list=PL123456789012345678901234').playlistId, 'PL123456789012345678901234')
  assert.throws(() => parsePlaylistInput('https://evil.example/playlist?list=PL123456789012345678901234'), /host_invalid/)
  assert.throws(() => parsePlaylistInput('https://youtu.be/watch?v=dQw4w9WgXcQ'), /host_invalid/)
  assert.throws(() => parsePlaylistInput('http://youtube.com/playlist?list=PL123456789012345678901234'), /scheme_invalid/)
  assert.throws(() => parsePlaylistInput('https://youtube.com/playlist?list=PL123456789012345678901234&foo=x'), /parameter_invalid/)
})

test('confirmation token is signed, expiring, and bound to admin/snapshot', () => {
  const token = issueConfirmation({ adminId: 'a1', snapshot: 'f'.repeat(64), playlistId: 'PL123456789012345678901234' }, 'test-secret', 2000)
  assert.equal(verifyConfirmation(token, 'test-secret', { adminId: 'a1', snapshot: 'f'.repeat(64) }).playlistId, 'PL123456789012345678901234')
  assert.throws(() => verifyConfirmation(token, 'wrong', { adminId: 'a1' }), /confirmation_invalid/)
  assert.throws(() => verifyConfirmation(token, 'test-secret', { adminId: 'a2' }), /binding_mismatch/)
})

const source = { channelId: 'UC12345678901234567890', playlistId: 'PL123456789012345678901234', policyVersion: 'v1' }
const singKing = { channelId: 'UCwTRjvjVge51X-ILJ4i22ew', playlistId: 'PL8D4Iby0Bmm-uQIcbRfHeUMd_YDSZDA39', policyVersion: 'v1' }
test('allowlist is bounded and rejects arbitrary playlist identities', () => {
  assert.deepEqual(parseAllowlist(JSON.stringify([source]))[0].playlistId, source.playlistId)
  assert.throws(() => parseAllowlist('[]'), /playlist_allowlist_invalid/)
  assert.throws(() => parseAllowlist(JSON.stringify([{ ...source, playlistId: 'bad' }])), /identity_invalid/)
})
test('source keys distinguish malformed syntax from an unconfigured but valid identity', () => {
  assert.deepEqual(parseSourceKey(`${singKing.channelId}:${singKing.playlistId}`), {
    channelId: singKing.channelId,
    playlistId: singKing.playlistId,
    sourceKey: `${singKing.channelId}:${singKing.playlistId}`,
  })
  assert.throws(() => parseSourceKey('not-a-source-key'), /playlist_source_key_invalid/)
  const configured = JSON.stringify([singKing])
  assert.equal(resolveAllowlistedSource(configured, `${singKing.channelId}:${singKing.playlistId}`).playlistId, singKing.playlistId)
  assert.equal(resolveAllowlistedSource(configured, `${source.channelId}:${source.playlistId}`), null)
})
test('playlist snapshot binds ordered video ids and metadata digest', () => {
  const snapshot = playlistSnapshot(source, { etag: 'page', items: [{ id: 'pi1', snippet: { position: 0, resourceId: { videoId: 'dQw4w9WgXcQ' } } }] })
  assert.equal(snapshot.ordered[0].videoId, 'dQw4w9WgXcQ')
  assert.equal(metadataDigest(snapshot, [{ id: 'dQw4w9WgXcQ', etag: 'video', status: { embeddable: true } }]).length, 64)
  assert.throws(() => playlistSnapshot(source, { items: [{ snippet: { position: 0 } }] }), /snapshot_invalid/)
})
test('title parser keeps uploader separate and rejects unsafe formats', () => {
  assert.deepEqual(parseTitle('Rick Astley - Never Gonna Give You Up (Karaoke Version)').artist, 'Rick Astley')
  assert.equal(parseTitle('Karaoke Brand - A Song').reason, 'artist_unsafe')
  assert.equal(parseTitle('Singer - Song Live at Wembley').reason, 'unsafe_title')
  assert.deepEqual(modeledCost(51), { playlistItemsList: 1, videosList: 2, total: 3 })
  assert.equal(parseTitle('Artist - Song', 'channel-name').reason, 'profile_unsupported')
})
test('trusted playlist availability ignores embeddable for native playback', () => {
  const hook = fs.readFileSync(require('node:path').join(__dirname, '..', 'pb_hooks', 'party_queue.pb.js'), 'utf8')
  const source = hook.match(/function classifyTrustedVideoAvailability\(video\) \{[\s\S]*?\n\}/)?.[0]
  assert.ok(source)
  const sandbox = {}; vm.runInNewContext(`${source}; this.classify = classifyTrustedVideoAvailability`, sandbox)
  assert.deepEqual(JSON.parse(JSON.stringify(sandbox.classify({ status: { privacyStatus: 'public', uploadStatus: 'processed', embeddable: false } }))), { unavailable: false, metadataMissing: 0, nonEmbeddable: 1 })
  assert.equal(sandbox.classify({ status: { privacyStatus: 'private', uploadStatus: 'processed' } }).unavailable, true)
  assert.equal(sandbox.classify({ status: { privacyStatus: 'public', uploadStatus: 'uploaded' } }).unavailable, true)
  assert.equal(sandbox.classify(null).metadataMissing, 1)
})

test('pending eligible candidates can be selected for approval', () => {
  assert.equal(isApprovable({ review_status: 'needs_review', identity_status: 'verified_source', artist: 'Artist', title: 'Song', classification: 'karaoke', eligible: false, embeddable: true, available: true, eligibility_reason: 'verified_source', alternatives_json: [] }), true)
})

test('PocketBase route validates bounded allowlist and separates unavailable from ownership mismatch', () => {
  const hook = fs.readFileSync(require('node:path').join(__dirname, '..', 'pb_hooks', 'party_queue.pb.js'), 'utf8')
  assert.match(hook, /playlist_allowlist_invalid/)
  assert.match(hook, /allowlist\.length > 12/)
  assert.match(hook, /identities\.has\(identity\)/)
  assert.match(hook, /throw new Error\('playlist_unavailable'\)/)
  assert.match(hook, /throw new Error\('playlist_owner_mismatch'\)/)
  assert.match(hook, /unavailableReasons/)
  assert.match(hook, /revalidate === true/)
  assert.match(hook, /revalidateKey = `playlist-revalidate:/)
  assert.match(hook, /playlist_revalidation_in_progress/)
  assert.match(hook, /metadataMissing/)
  assert.match(hook, /const reserve = modeledVideos \* 3/)
  assert.match(hook, /playlist_revalidation_state_invalid/)
  assert.match(hook, /if \(!priorSnapshot && revalidate\)/)
  assert.match(hook, /importPhase = 'owner_fetch'/)
  assert.match(hook, /importPhase = 'snapshot_verify'; const snapshotFingerprint/)
  assert.match(hook, /importPhase = 'settle_success'; recordYoutubeOperation/)
  assert.match(hook, /playlist_import_settle_success_failed/)
  assert.match(hook, /playlist_import_persist_results_failed/)
  assert.match(hook, /const phaseCodes = \['owner_fetch'/)
  assert.match(hook, /importPhase = 'song_save'/)
  assert.match(hook, /playlist_snapshot_schema_mismatch/)
  assert.match(hook, /playlist_snapshot_token_too_long/)
  ;['identity', 'page', 'digest', 'ids', 'dates'].forEach((stage) => assert.match(hook, new RegExp(`playlist_import_snapshot_${stage}_save_failed`)))
  assert.match(hook, /function findPlaylistSnapshot\(db, sourceKey, pageToken, fingerprint\)/)
  assert.match(hook, /String\(str\(row, 'page_token'\) \|\| ''\) === targetPage/)
  assert.match(hook, /playlist_snapshot_ambiguous/)
  assert.match(hook, /findRecordsByFilter\('karaoke_playlist_snapshots'.*', 3, 0/)
  assert.match(hook, /playlist_snapshot_lookup_failed/)
  assert.match(hook, /TRUSTED_PLAYLIST_ELIGIBILITY_POLICY = 'native-playback-v2'/)
  assert.match(hook, /TRUSTED_PLAYLIST_ELIGIBILITY_POLICY \} = globalThis.__partyQueue/)
  assert.match(hook, /function classifyTrustedVideoAvailability\(video\)/)
  assert.ok((hook.match(/classifyTrustedVideoAvailability\(video\)/g) || []).length >= 3)
  assert.match(hook, /selection_operation_binding_mismatch/)
  assert.match(hook, /approved_count.*excluded_json/)
  assert.match(hook, /cursor >= \(Array\.isArray\(ids\) \? ids\.length : 0\)/)
  assert.match(hook, /source_filter_digest/)
  assert.match(hook, /policy: 'approval-v1'/)
  assert.match(hook, /const token = parser\.issueConfirmation/)
  assert.match(hook, /confirmation\.expectedCounts/)
  assert.match(hook, /confirmation\.pageToken/)
  assert.match(hook, /str\(row, 'status'\) === 'used'/)
  assert.match(hook, /completed = Boolean\(replayClaim && \['ready', 'complete'\]/)
  assert.match(hook, /const usedConfirmation = Boolean\(persistedConfirmation && str\(persistedConfirmation, 'status'\) === 'used'\)/)
  assert.match(hook, /source_id = \{:\w+\}/)
  assert.match(hook, /playlistScope \? str\(song, 'source'\) === 'youtube_playlist' && str\(song, 'source_id'\) === scopedSource/)
  assert.match(hook, /UC\[A-Za-z0-9_\-\]\{20,\}:\(\?:PL\|UU\|LL\|FL\|RD\)/)
})
