// Additive trusted-playlist provenance and operation-class ledger. Existing search/import history remains intact.
migrate((app) => {
  const find = (name) => { try { return app.findCollectionByNameOrId(name) } catch (_) { return null } }
  const add = (collection, name, type, options = {}) => { try { if (collection.fields.getByName(name)) return } catch (_) {} collection.fields.add(new Field({ name, type, ...options })) }
  const songs = find('karaoke_songs')
  if (songs) { for (const [name, type, options] of [['playlist_source_id', 'text', { max: 120 }], ['playlist_position', 'number', { min: 0, noDecimal: true }], ['playlist_snapshot_fingerprint', 'text', { max: 64 }], ['metadata_digest', 'text', { max: 64 }]]) add(songs, name, type, options); app.save(songs) }
  let operations = find('karaoke_youtube_operations')
  if (!operations) { operations = new Collection({ name: 'karaoke_youtube_operations', type: 'base', listRule: null, viewRule: null, createRule: null, updateRule: null, deleteRule: null, fields: [{ name: 'day_key', type: 'text', required: true, max: 16 }, { name: 'operation_class', type: 'text', required: true, max: 80 }, { name: 'modeled_units', type: 'number', min: 0, noDecimal: true }, { name: 'observed_calls', type: 'number', min: 0, noDecimal: true }, { name: 'source_key', type: 'text', max: 240 }, { name: 'snapshot_fingerprint', type: 'text', max: 64 }], indexes: ['CREATE UNIQUE INDEX idx_karaoke_youtube_operation_class ON karaoke_youtube_operations (day_key, operation_class, source_key, snapshot_fingerprint)'] }); app.save(operations) }
  let snapshots = find('karaoke_playlist_snapshots')
  if (!snapshots) { snapshots = new Collection({ name: 'karaoke_playlist_snapshots', type: 'base', listRule: null, viewRule: null, createRule: null, updateRule: null, deleteRule: null, fields: [{ name: 'source_key', type: 'text', required: true, max: 240 }, { name: 'policy_version', type: 'text', required: true, max: 40 }, { name: 'page_token', type: 'text', max: 240 }, { name: 'next_page_token', type: 'text', max: 240 }, { name: 'snapshot_fingerprint', type: 'text', required: true, max: 64 }, { name: 'metadata_digest', type: 'text', max: 64 }, { name: 'ordered_video_ids_json', type: 'json' }, { name: 'retrieved_at', type: 'date' }, { name: 'owner_validated_at', type: 'date' }], indexes: ['CREATE UNIQUE INDEX idx_karaoke_playlist_snapshot ON karaoke_playlist_snapshots (source_key, page_token, snapshot_fingerprint)'] }); app.save(snapshots) }
  else { add(snapshots, 'owner_validated_at', 'date'); app.save(snapshots) }
  if (!find('karaoke_playlist_claims')) app.save(new Collection({ name: 'karaoke_playlist_claims', type: 'base', listRule: null, viewRule: null, createRule: null, updateRule: null, deleteRule: null, fields: [{ name: 'claim_key', type: 'text', required: true, max: 320 }, { name: 'status', type: 'select', required: true, maxSelect: 1, values: ['in_progress', 'ready', 'failed'] }, { name: 'quota_day_key', type: 'text', required: true, max: 16 }, { name: 'reserved_units', type: 'number', min: 0, noDecimal: true }, { name: 'spent_units', type: 'number', min: 0, noDecimal: true }, { name: 'owner_token', type: 'text', max: 120 }, { name: 'lease_expires_at', type: 'date' }, { name: 'payload_json', type: 'json' }, { name: 'error_code', type: 'text', max: 120 }], indexes: ['CREATE UNIQUE INDEX idx_karaoke_playlist_claim_key ON karaoke_playlist_claims (claim_key)'] }))
}, () => {})
