'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const hook = fs.readFileSync(path.join(__dirname, '..', 'pb_hooks', 'party_queue.pb.js'), 'utf8')
const repairMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512300_repair_song_catalog_collection.js'), 'utf8')
const quotaMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512000_youtube_quota.js'), 'utf8')
const claimsMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512100_youtube_claims.js'), 'utf8')
const payloadMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512200_youtube_payloads.js'), 'utf8')
const fieldRepairMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512400_repair_catalog_field_presence.js'), 'utf8')
const checkpointRepairMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512500_repair_catalog_checkpoint_schema.js'), 'utf8')
const offsetRepairMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512600_repair_catalog_chunk_offset_required.js'), 'utf8')
const fieldApiRepairMigration = fs.readFileSync(path.join(__dirname, '..', 'pb_migrations', '1784512700_repair_catalog_checkpoint_field_api.js'), 'utf8')

test('catalog callbacks resolve their helpers through the reload-safe global contract', () => {
  const replacement = hook.match(/routerAdd\('POST', '\/api\/karaoke\/tablet\/catalog\/\{id\}\/replace'[\s\S]*?\n}\)/)
  assert.ok(replacement)
  assert.match(replacement[0], /require\(__hooks \+ '\/party_queue\.pb\.js'\)/)
  assert.match(replacement[0], /globalThis\.__partyQueue/)
  assert.match(replacement[0], /YOUTUBE_ID/)
  assert.match(replacement[0], /body, now, id/)
  assert.match(replacement[0], /c\.request\.pathValue\('id'\)/)
})

test('catalog API exposes frontend review and pagination contract', () => {
  assert.match(hook, /totalItems, totalPages/)
  assert.match(hook, /reviewState:/)
  assert.match(hook, /reviewState: str\(song, 'review_status'\) \|\| 'unreviewed'/)
  assert.match(hook, /runInTransaction\(\(tx\) =>/)
  assert.match(hook, /return c\.json\(200, result\)/)
  assert.match(hook, /const totalItems = allRows\.length/)
  assert.match(hook, /catalog\/\{id\}\/review/)
})

test('checkpoint health is tablet-only and exposes only fixed structural metadata', () => {
  const endpoint = hook.match(/routerAdd\('GET', '\/api\/karaoke\/tablet\/catalog\/checkpoint-health',[\s\S]*?\n}\)/)
  assert.ok(endpoint)
  assert.match(endpoint[0], /require\(__hooks \+ '\/party_queue\.pb\.js'\)/)
  assert.match(endpoint[0], /const \{ auth, tablet, json, catalogCheckpointHealth \} = globalThis\.__partyQueue/)
  assert.match(endpoint[0], /tablet\(auth\(c\)\)/)
  assert.match(endpoint[0], /catalog_checkpoint_unavailable/)
  assert.match(endpoint[0], /return c\.json\(200, health\)/)
  assert.doesNotMatch(endpoint[0], /records\(|findRecords|findFirstRecord|collection\.indexes/)
  assert.match(hook, /const CATALOG_CHECKPOINT_HEALTH_FIELDS = \{[\s\S]*\['batch_key', 'text', true\]/)
  assert.match(hook, /\['import', 'relation', true\]/)
  assert.match(hook, /relationTargetMatches/)
  assert.match(hook, /hasExpectedUniqueIndex/)
  assert.match(hook, /catalogFieldType\(rawRelation\) === 'relation'/)
  assert.match(hook, /typeof field\.type === 'function'/)
  assert.match(hook, /const fieldType = catalogFieldType\(field\)/)
  assert.match(hook, /const type = CATALOG_CHECKPOINT_HEALTH_TYPES\.includes\(fieldType\) \? fieldType : field \? 'other' : null/)
  assert.match(hook, /imports: \{ present: true, hasExpectedUniqueIndex: importsUniqueIndex, fields: importFields \}/)
  assert.match(hook, /chunks: \{ present: true, hasExpectedUniqueIndex: chunksUniqueIndex, relationTargetMatches, fields: chunkFields \}/)
})

test('catalog import uses immutable manifest/chunk metadata and derived classification', () => {
  assert.match(hook, /manifestFingerprint/)
  assert.match(hook, /chunk_source_mismatch/)
  assert.match(hook, /classifyCatalogItem\(item\)/)
  assert.doesNotMatch(hook, /classes\.includes\(item\.classification\)/)
  assert.match(hook, /replacement_unavailable/)
  assert.match(hook, /offset !== num\(batch, 'cursor'\)/)
  assert.match(hook, /chunk_out_of_order/)
  assert.match(hook, /fallback_lyric/)
  assert.match(hook, /fallback_audio/)
  assert.match(hook, /Persist a newly created batch before using its id/)
  assert.match(hook, /set\(batch, 'total', total\); tx\.save\(batch\)/)
})

test('catalog completion verifies canonical content and source metadata digest', () => {
  assert.match(hook, /function catalogFinalDigest\(source, total, items\)/)
  assert.match(hook, /source: \{ url: String\(source\?\.url/)
  assert.match(hook, /retrievedAt: String\(source\?\.retrievedAt/)
  assert.match(hook, /final_digest_mismatch/)
  assert.match(hook, /catalogFinalDigest, normalized/)
})

test('identity alternatives and review history are append-only and idempotent', () => {
  assert.match(hook, /identity_key = \{:\s*identity\}/)
  assert.match(hook, /alternatives_json/)
  assert.match(hook, /!list\.some\(\(candidate\) => String\(candidate\.youtubeId \|\| ''\) === youtubeId\)/)
  assert.match(hook, /action: 'review'/)
  assert.match(hook, /action: 'replacement'/)
  assert.match(hook, /set\(song, 'review_history_json', events\)/)
})

test('review and replacement history mutations are transactional and untruncated', () => {
  const review = hook.match(/routerAdd\('POST', '\/api\/karaoke\/tablet\/catalog\/\{id\}\/review',[\s\S]*?\n}\)/)?.[0] || ''
  const replace = hook.match(/routerAdd\('POST', '\/api\/karaoke\/tablet\/catalog\/\{id\}\/replace',[\s\S]*?\n}\)/)?.[0] || ''
  assert.match(review, /\$app\.runInTransaction\(\(tx\)/)
  assert.match(replace, /\$app\.runInTransaction\(\(tx\)/)
  assert.doesNotMatch(review + replace, /events\.slice\(/)
})

test('fixture import failures log only bounded batch diagnostics', () => {
  assert.match(hook, /function catalogImportFailureStage\(stage\)/)
  assert.match(hook, /function logCatalogImportFailure\(stage, offset, itemCount\)/)
  assert.match(hook, /const stages = \['batch_create', 'batch_validate', 'song_save', 'chunk_save', 'batch_finalize'\]/)
  assert.match(hook, /return stages\.includes\(stage\) \? stage : 'unknown'/)
  assert.match(hook, /stage=\$\{safeStage\}, offset=\$\{safeOffset\}, itemCount=\$\{safeItemCount\}/)
  assert.doesNotMatch(hook, /batchKeyLength|batchKeyHash|\$\{message\}|errorMessage/)
  assert.match(hook, /const chunkFingerprint = live \? requestFingerprint : hash\(JSON\.stringify\(canonicalize\(\{ offset, items \}\)\)\)\n  let diagnosticStage = 'batch_create'/)
  assert.match(hook, /diagnosticStage = 'song_save'; tx\.save\(song\)/)
  assert.match(hook, /diagnosticStage = 'chunk_save'; tx\.save\(chunk\)/)
  assert.match(hook, /diagnosticStage = 'batch_finalize'; tx\.save\(batch\)/)
  assert.match(hook, /logCatalogImportFailure\(diagnosticStage, offset, items\.length\)/)
  assert.match(hook, /const extra = !live \? \{ failureStage: catalogImportFailureStage\(diagnosticStage\) \} : undefined/)
  assert.match(hook, /'Catalog import failed', extra\)/)
  assert.doesNotMatch(hook, /failureStage:\s*(?:error|input|source|batchKey|manifestFingerprint|chunkFingerprint)/)
  assert.match(hook, /globalThis\.__partyQueue = \{[\s\S]*catalogImportFailureStage, logCatalogImportFailure \}/)
  assert.match(hook, /fetchYoutubeCandidates, dayKey, random, id, str, catalogImportFailureStage, logCatalogImportFailure \} = globalThis\.__partyQueue/)
})

test('live catalog discovery stays server-side and records quota/availability metadata', () => {
  assert.match(hook, /YOUTUBE_API_KEY/)
  assert.match(hook, /youtube\/v3\/search\?part=snippet&type=video/)
  assert.match(hook, /youtube\/v3\/videos\?part=snippet,contentDetails,status,statistics/)
  assert.match(hook, /quota_used/)
  assert.match(hook, /requestedMaxResults/)
  assert.match(hook, /chunk_replay/)
  assert.match(hook, /timeout: 15/)
  assert.match(hook, /youtube_quota_exhausted/)
  assert.match(hook, /embeddable === true/)
  assert.doesNotMatch(hook, /return json\(c, 503, 'youtube_import_unavailable'/)
})

test('live claims persist payload and quota day before catalog completion', () => {
  assert.match(hook, /payload_json', \{ items, total, spent \}/)
  assert.match(hook, /set\(claim, 'status', 'ready'\)/)
  assert.match(hook, /set\(claim, 'status', 'complete'\)/)
  assert.match(hook, /quota_day_key/)
  assert.match(hook, /day_key = \{:\s*day\}/)
  assert.match(hook, /set\(chunk, 'payload_json', items\)/)
  assert.match(hook, /America\/Los_Angeles/)
  assert.match(hook, /ownerToken = str\(claim, 'owner_token'\) \|\| ownerToken/)
  assert.match(hook, /!\['ready', 'complete'\]\.includes\(str\(existingClaim, 'status'\)\)/)
  assert.match(hook, /const quotaDay = dayKey\(\)/)
})

test('live fetch failures release the persisted reservation for retry', () => {
  assert.match(hook, /set\(claim, 'status', 'failed'\)/)
  assert.match(hook, /set\(claim, 'reserved_units', 0\)/)
  assert.match(hook, /Math\.max\(0, num\(quota, 'reserved'\) - reserved\)/)
})

test('claim cleanup is owned by the current invocation', () => {
  assert.match(hook, /owner_token/)
  assert.match(hook, /str\(claim, 'owner_token'\) === ownerToken/)
  assert.match(hook, /error\.quotaCost/)
  assert.match(hook, /attemptedCost/)
  assert.match(hook, /globalThis\.__partyQueue \|\| \{\}/)
  assert.match(hook, /globalThis\.__partyQueue = .*youtubeRequest/)
  assert.match(hook, /lease_expires_at/)
  assert.match(hook, /oldReserved.*oldDay/)
  assert.match(hook, /youtube_claim_stale_owner/)
  assert.match(hook, /if \(!items\.length\)/)
  assert.match(hook, /\['ready', 'complete'\]\.includes\(str\(claim, 'status'\)\)/)
})

test('catalog repair preserves records while rebinding stale relation metadata', () => {
  assert.match(repairMigration, /songRelation\.collectionId = songs\.id/)
  assert.match(repairMigration, /app\.save\(queue\)/)
  assert.match(repairMigration, /queue records remain[\s\S]*song ids/)
  assert.match(repairMigration, /importRelation\.collectionId = imports\.id/)
})

test('catalog repair keeps catalog collections private and restores field options', () => {
  assert.match(repairMigration, /const makePrivate = \(collection\)/)
  assert.match(repairMigration, /collection\[key\] !== null/)
  assert.match(repairMigration, /const ensureField = \(collection, name, type, options = \{\}\)/)
  assert.match(repairMigration, /if \(field\.type !== type\) return false/)
  assert.match(repairMigration, /required: false, default: false/)
})

test('catalog field repairs handle PocketBase undefined field lookups', () => {
  assert.match(repairMigration, /try \{ existing = collection\.fields\.getByName\(name\) \} catch \(_\) \{\}/)
  assert.match(repairMigration, /if \(existing\) return false/)
  assert.match(fieldRepairMigration, /PocketBase 0\.39 returns undefined/)
  assert.match(fieldRepairMigration, /if \(field\) return false/)
  assert.match(fieldRepairMigration, /\['review_status', 'select'/)
  assert.match(fieldRepairMigration, /app\.save\(songs\)/)
  assert.match(fieldRepairMigration, /classification = "" \|\| review_status = ""/)
  assert.match(fieldRepairMigration, /record\.set\('classification', 'unknown'\)/)
  assert.match(fieldRepairMigration, /record\.set\('review_status', 'unreviewed'\)/)
  assert.match(fieldRepairMigration, /nonblank classifications and review decisions are preserved/)
  assert.match(fieldRepairMigration, /offsetField\.required = false/)
})

test('YouTube ledger migrations tolerate missing retained collections without record rewrites', () => {
  for (const migration of [quotaMigration, claimsMigration, payloadMigration]) {
    assert.match(migration, /try \{ return app\.findCollectionByNameOrId\(name\) \} catch \(_\) \{ return null \}/)
    assert.match(migration, /const makePrivate = \(collection\)/)
    assert.match(migration, /const ensureField = \(collection, name, type, options = \{\}\)/)
  }
  assert.match(quotaMigration, /idx_karaoke_youtube_quota_day/)
  assert.match(quotaMigration, /historical duplicate[\s\S]*records remain/)
  assert.match(claimsMigration, /idx_karaoke_youtube_claim_key/)
  assert.match(claimsMigration, /status\.type === 'select'/)
  assert.match(payloadMigration, /name: 'karaoke_catalog_imports'/)
  assert.match(payloadMigration, /name: 'karaoke_catalog_import_chunks'/)
  assert.match(payloadMigration, /relation\.collectionId = imports\.id/)
})

test('checkpoint repair restores only missing retained import fields', () => {
  assert.match(checkpointRepairMigration, /undefined PocketBase field lookup/)
  assert.match(checkpointRepairMigration, /if \(field\) return false/)
  assert.match(checkpointRepairMigration, /name: 'karaoke_catalog_imports'/)
  assert.match(checkpointRepairMigration, /name: 'karaoke_catalog_import_chunks'/)
  assert.match(checkpointRepairMigration, /\['payload_json', 'json'/)
  assert.match(checkpointRepairMigration, /relation\.collectionId = imports\.id/)
  assert.match(checkpointRepairMigration, /without changing import or chunk records/)
  assert.match(checkpointRepairMigration, /const canonicalImportFields/)
  assert.match(checkpointRepairMigration, /const canonicalChunkFields/)
  assert.match(checkpointRepairMigration, /fail this migration clearly for operator repair/)
  assert.doesNotMatch(checkpointRepairMigration, /try \{ app\.save\(imports\) \} catch/)
  assert.doesNotMatch(checkpointRepairMigration, /try \{ app\.save\(chunks\) \} catch/)
})

test('forward chunk offset repair makes retained zero checkpoints writable', () => {
  assert.match(offsetRepairMigration, /karaoke_catalog_import_chunks/)
  assert.match(offsetRepairMigration, /offset\.type !== 'number'/)
  assert.match(offsetRepairMigration, /offset\.required\)/)
  assert.match(offsetRepairMigration, /offset\.required = false/)
  assert.match(offsetRepairMigration, /app\.save\(chunks\)/)
  assert.match(offsetRepairMigration, /without rewriting any records or other schema/)
  assert.match(fieldApiRepairMigration, /typeof offset\.type === 'function'/)
  assert.match(fieldApiRepairMigration, /offset\.type\(\)/)
  assert.match(fieldApiRepairMigration, /type !== 'number'/)
  assert.match(fieldApiRepairMigration, /offset\.required !== true/)
  assert.match(fieldApiRepairMigration, /offset\.required = false/)
  assert.doesNotMatch(fieldApiRepairMigration, /delete|remove/)
})
