'use strict'
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const { execFileSync, spawn } = require('node:child_process')
test('PocketBase catalog review enforces auth, policy, collision, and transactional demotion', { skip: !process.env.POCKETBASE_BIN }, async (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'karaoke-review-pb-')); fs.cpSync(path.join(__dirname, '..', 'pb_migrations'), path.join(root, 'pb_migrations'), { recursive: true }); fs.cpSync(path.join(__dirname, '..', 'pb_hooks'), path.join(root, 'pb_hooks'), { recursive: true }); const dataDir = path.join(root, 'pb_data'); const bin = process.env.POCKETBASE_BIN
  execFileSync(bin, ['migrate', 'up', '--dir', dataDir]); execFileSync(bin, ['superuser', 'upsert', 'review@test.invalid', 'CorrectHorseBatteryStaple123!', '--dir', dataDir]); const port = 19900 + Math.floor(Math.random() * 80); const server = spawn(bin, ['serve', '--dir', dataDir, `--http=127.0.0.1:${port}`], { stdio: 'ignore' }); t.after(() => server.kill('SIGTERM')); const base = `http://127.0.0.1:${port}`
  for (let i = 0; i < 60; i++) { try { if ((await fetch(`${base}/api/health`)).ok) break } catch (_) {} await new Promise((r) => setTimeout(r, 100)) }
  const call = async (url, method, payload, token) => { const response = await fetch(base + url, { method, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: payload === undefined ? undefined : JSON.stringify(payload) }); let json = {}; try { json = await response.json() } catch (_) {} return { status: response.status, json } }
  const su = await call('/api/collections/_superusers/auth-with-password', 'POST', { identity: 'review@test.invalid', password: 'CorrectHorseBatteryStaple123!' }); assert.equal(su.status, 200); const user = await call('/api/collections/users/records', 'POST', { email: 'review-tablet@test.invalid', username: 'reviewtablet', password: 'TabletPassword123!', passwordConfirm: 'TabletPassword123!', role: 'tablet_admin' }, su.json.token); assert.equal(user.status, 200); const tablet = await call('/api/collections/users/auth-with-password', 'POST', { identity: 'review-tablet@test.invalid', password: 'TabletPassword123!' }); assert.equal(tablet.status, 200)
  assert.equal((await call('/api/karaoke/tablet/catalog/nope/review', 'POST', { reviewState: 'approved' })).status, 403)
  const baseSong = { artist: 'Artist', title: 'Song', eligible: false, classification: 'karaoke', classification_confidence: 0.95, review_status: 'needs_review', identity_status: 'verified_source', mb_match_status: 'not_attempted', identity_key: 'artist|song', review_history_json: [] }; const missing = await call('/api/collections/karaoke_songs/records', 'POST', { ...baseSong, youtube_id: 'missident01', identity_status: 'missing', artist: '', identity_key: 'missing|missident01' }, su.json.token); assert.equal(missing.status, 200); const malformed = await call('/api/karaoke/tablet/catalog/' + missing.json.id + '/review', 'POST', { reviewState: 'approved' }, tablet.json.token); assert.equal(malformed.status, 409); assert.equal(malformed.json.error, 'missing_identity')
  const reject = await call('/api/karaoke/tablet/catalog/' + missing.json.id + '/review', 'POST', { reviewState: 'rejected', note: 'operator rejection' }, tablet.json.token); assert.equal(reject.status, 200); assert.equal(reject.json.eligible, false); assert.equal(reject.json.reviewState, 'rejected')
  const first = await call('/api/collections/karaoke_songs/records', 'POST', { ...baseSong, youtube_id: 'firstsong01', title: 'Collision', identity_key: 'same|identity' }, su.json.token); const second = await call('/api/collections/karaoke_songs/records', 'POST', { ...baseSong, youtube_id: 'secondsong1', title: 'Collision', identity_key: 'same|identity' }, su.json.token); assert.equal(first.status, 200); assert.equal(second.status, 200); const collision = await call('/api/karaoke/tablet/catalog/' + first.json.id + '/review', 'POST', { reviewState: 'approved' }, tablet.json.token); assert.equal(collision.status, 409); assert.equal(collision.json.error, 'identity_conflict')
})
