'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const hook = fs.readFileSync(path.join(__dirname, '..', 'pb_hooks', 'controller_protocol.pb.js'), 'utf8')

test('authenticated controller resume and state reports refresh device liveness atomically', () => {
  const sessionRoute = hook.slice(hook.indexOf("routerAdd('POST', '/api/karaoke/controllers/sessions'"), hook.indexOf("routerAdd('POST', '/api/karaoke/controller-commands'"))
  const stateRoute = hook.slice(hook.indexOf("routerAdd('PUT', '/api/karaoke/controllers/state'"), hook.indexOf("routerAdd('POST', '/api/karaoke/controllers/enrollment-grants'"))
  assert.match(sessionRoute, /previous && number\(previous, 'generation'\) === currentGeneration[\s\S]*set\(txAuth, 'last_seen_at', now\(\)\); txApp\.save\(txAuth\)/)
  assert.match(stateRoute, /set\(device, 'last_seen_at', now\(\)\); txApp\.save\(device\)[\s\S]*set\(state, 'device'/)
})

test('enrollment grants are hashed, expiring, revocable, and operator-scoped', () => {
  const createRoute = hook.slice(hook.indexOf("routerAdd('POST', '/api/karaoke/controllers/enrollment-grants'"), hook.indexOf("routerAdd('GET', '/api/karaoke/controllers/enrollment-grants/{id}'"))
  const enrollRoute = hook.slice(hook.indexOf("routerAdd('POST', '/api/karaoke/controllers/enroll'"), hook.indexOf("routerAdd('POST', '/api/karaoke/controllers/sessions'"))
  assert.match(createRoute, /isTabletAdmin\(auth\)/)
  assert.match(createRoute, /set\(grant, 'grant_hash', hashSecret\(token\)\)/)
  assert.match(createRoute, /set\(grant, 'short_code_hash', hashSecret\(shortCode\)\)/)
  assert.match(createRoute, /set\(grant, 'operator_id', recordId\(auth\)\)/)
  assert.match(createRoute, /used_at = "" && revoked_at = "" && expires_at > \{:\s*now\}/)
  assert.match(enrollRoute, /enrollment_grant_wrong_server/)
  assert.match(enrollRoute, /enrollment_grant_replayed/)
  assert.match(enrollRoute, /enrollment_grant_expired/)
  assert.match(enrollRoute, /enrollment_grant_revoked/)
  assert.match(enrollRoute, /normalizeShortCode\(body\.shortCode\)/)
  assert.match(enrollRoute, /const actualHost = requestHost\(c\)/)
  assert.match(enrollRoute, /hostMatches\(actualHost, suppliedHost\)/)
  assert.match(enrollRoute, /hostMatches\(actualHost, expectedHost\)/)
  assert.doesNotMatch(enrollRoute, /return c\.json\([^\n]+token[^\n]+shortCode/)
})

test('grant status requires a non-revoked device, live current session, matching connected state, and fresh observation', () => {
  const route = hook.slice(hook.indexOf("routerAdd('GET', '/api/karaoke/controllers/enrollment-grants/{id}'"), hook.indexOf("routerAdd('POST', '/api/karaoke/controllers/enrollment-grants/{id}/revoke'"))
  assert.match(route, /generation = \{:\s*generation\}/)
  assert.match(route, /string\(candidate, 'expires_at'\)\)\.getTime\(\) > Date\.now\(\)/)
  assert.match(route, /number\(stateRecord, 'session_generation'\) === generation/)
  assert.match(route, /freshObservedAt\(string\(stateRecord, 'observed_at'\)\)/)
  assert.match(route, /string\(stateRecord, 'connection_state'\) === 'connected'/)
  assert.match(route, /!bool\(device, 'revoked'\)/)
  assert.match(route, /state = string\(grant, 'revoked_at'\) \|\| \(device && bool\(device, 'revoked'\)\)/)
  assert.match(route, /stateGeneration: stateRecord \? number\(stateRecord, 'session_generation'\) : null/)
  assert.match(route, /sessionActive: Boolean\(session\)/)
  assert.doesNotMatch(route, /session:\s*session \? /)
  assert.doesNotMatch(route, /id: recordId\(session\)/)
  assert.match(route, /observedAt: stateRecord \? string\(stateRecord, 'observed_at'\) \|\| null : null/)
})
