'use strict'

// Run against a real PocketBase binary with:
// POCKETBASE_BIN=/path/to/pocketbase node --test pocketbase/protocol/controller_protocol.integration.node.cjs
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const http = require('node:http')
const { execFileSync, spawn } = require('node:child_process')

const binary = process.env.POCKETBASE_BIN

test('PocketBase controller protocol authorization and transitions', { skip: !binary }, async (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'karaoke-pb-'))
  fs.cpSync(path.join(__dirname, '..', 'pb_migrations'), path.join(root, 'pb_migrations'), { recursive: true })
  fs.cpSync(path.join(__dirname, '..', 'pb_hooks'), path.join(root, 'pb_hooks'), { recursive: true })
  const dataDir = path.join(root, 'pb_data')
  execFileSync(binary, ['migrate', 'up', '--dir', dataDir], { stdio: 'ignore' })
  execFileSync(binary, ['superuser', 'upsert', 'operator@example.test', 'CorrectHorseBatteryStaple123!', '--dir', dataDir], { stdio: 'ignore' })
  const port = 19000 + Math.floor(Math.random() * 500)
  const server = spawn(binary, ['serve', '--dir', dataDir, `--http=127.0.0.1:${port}`], { stdio: 'ignore' })
  t.after(() => server.kill('SIGTERM'))
  const base = `http://127.0.0.1:${port}`
  for (let i = 0; i < 50; i++) {
    try { if ((await fetch(`${base}/api/health`)).ok) break } catch (_) {}
    await new Promise((resolve) => setTimeout(resolve, 100))
  }
  const call = async (url, method, body, token, extraHeaders = {}) => {
    const response = await fetch(`${base}${url}`, { method, headers: { 'content-type': 'application/json', ...extraHeaders, ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) })
    let json = {}
    try { json = await response.json() } catch (_) {}
    return { status: response.status, json }
  }
  const callWithHost = (url, method, body, host, token, extraHeaders = {}) => new Promise((resolve, reject) => {
    const payload = body === undefined ? undefined : JSON.stringify(body)
    const request = http.request({ hostname: '127.0.0.1', port, path: url, method, headers: { host, 'content-type': 'application/json', ...extraHeaders, ...(token ? { authorization: `Bearer ${token}` } : {}), ...(payload ? { 'content-length': Buffer.byteLength(payload) } : {}) } }, (response) => {
      let text = ''
      response.setEncoding('utf8')
      response.on('data', (chunk) => { text += chunk })
      response.on('end', () => {
        let json = {}
        try { json = JSON.parse(text) } catch (_) {}
        resolve({ status: response.statusCode, json })
      })
    })
    request.on('error', reject)
    if (payload) request.write(payload)
    request.end()
  })
  const readSseRecord = async (predicate, reader) => {
    let text = ''
    for (let i = 0; i < 30; i++) {
      const chunk = await Promise.race([reader.read(), new Promise((resolve) => setTimeout(() => resolve({ done: true }), 500))])
      if (chunk.done) break
      text += new TextDecoder().decode(chunk.value)
      const data = text.match(/data:(\{.*\})/g)?.map((line) => line.slice(5)).find((line) => {
        try { return predicate(JSON.parse(line)) } catch (_) { return false }
      })
      if (data) return JSON.parse(data)
    }
    throw new Error(`missing realtime record event: ${text}`)
  }
  const superAuth = await call('/api/collections/_superusers/auth-with-password', 'POST', { identity: 'operator@example.test', password: 'CorrectHorseBatteryStaple123!' })
  assert.equal(superAuth.status, 200)
  const superToken = superAuth.json.token
  const user = await call('/api/collections/users/records', 'POST', { email: 'tablet@example.test', password: 'TabletPassword123!', passwordConfirm: 'TabletPassword123!', role: 'tablet_admin' }, superToken)
  assert.equal(user.status, 200)
  const tabletAuth = await call('/api/collections/users/auth-with-password', 'POST', { identity: 'tablet@example.test', password: 'TabletPassword123!' })
  assert.equal(tabletAuth.status, 200)
  const tabletToken = tabletAuth.json.token
  assert.equal((await call('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: '127.0.0.1', destination: '127.0.0.1' })).status, 403)
  const proxyGrant = await callWithHost('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: 'karaoke-test.app.starsummit.net', destination: 'karaoke-test.app.starsummit.net' }, 'starsummit-pocketbase-internal:8090', tabletToken, { 'x-starsummit-public-host': 'karaoke-test.app.starsummit.net' })
  assert.equal(proxyGrant.status, 201, JSON.stringify(proxyGrant))
  const proxyEnrolled = await callWithHost('/api/karaoke/controllers/enroll', 'POST', { token: proxyGrant.json.token, deviceName: 'proxy tablet', serverHost: 'karaoke-test.app.starsummit.net', destination: 'karaoke-test.app.starsummit.net' }, 'starsummit-pocketbase-internal:8090', undefined, { 'x-starsummit-public-host': 'karaoke-test.app.starsummit.net' })
  assert.equal(proxyEnrolled.status, 201, JSON.stringify(proxyEnrolled))
  const directHeaderSpoof = await callWithHost('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: 'karaoke-test.app.starsummit.net', destination: 'karaoke-test.app.starsummit.net' }, 'evil.test', tabletToken, { 'x-starsummit-public-host': 'karaoke-test.app.starsummit.net' })
  assert.equal(directHeaderSpoof.status, 400, JSON.stringify(directHeaderSpoof))
  const grant = await call('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: '127.0.0.1', destination: '127.0.0.1' }, tabletToken)
  assert.equal(grant.status, 201)
  const persistedGrant = await call(`/api/collections/controller_enrollment_grants/records/${grant.json.id}`, 'GET', undefined, superToken)
  assert.equal(persistedGrant.status, 200, JSON.stringify(persistedGrant))
  assert.notEqual(persistedGrant.json.grant_hash, grant.json.token)
  assert.notEqual(persistedGrant.json.short_code_hash, grant.json.shortCode)
  assert.equal(Object.prototype.hasOwnProperty.call(persistedGrant.json, 'token'), false)
  assert.equal(Object.prototype.hasOwnProperty.call(persistedGrant.json, 'shortCode'), false)
  const wrongServer = await call('/api/karaoke/controllers/enroll', 'POST', { token: grant.json.token, deviceName: 'wrong server', serverHost: 'evil.test', destination: '127.0.0.1' })
  assert.equal(wrongServer.status, 410)
  assert.equal(wrongServer.json.error, 'enrollment_grant_wrong_server')
  assert.doesNotMatch(JSON.stringify(wrongServer.json), new RegExp(grant.json.token))
  const spoofedRequestHost = await callWithHost('/api/karaoke/controllers/enroll', 'POST', { token: grant.json.token, deviceName: 'spoofed request host', serverHost: '127.0.0.1', destination: '127.0.0.1' }, 'evil.test')
  assert.equal(spoofedRequestHost.status, 410)
  assert.equal(spoofedRequestHost.json.error, 'enrollment_grant_wrong_server')
  assert.doesNotMatch(JSON.stringify(spoofedRequestHost.json), new RegExp(grant.json.token))
  const grantStatusBefore = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusBefore.status, 200, JSON.stringify(grantStatusBefore))
  assert.equal(grantStatusBefore.json.state, 'active')
  assert.doesNotMatch(JSON.stringify(grantStatusBefore.json), new RegExp(grant.json.token))
  assert.doesNotMatch(JSON.stringify(grantStatusBefore.json), new RegExp(grant.json.shortCode))
  const enrolled = await call('/api/karaoke/controllers/enroll', 'POST', { token: grant.json.token, deviceName: 'integration tablet', serverHost: '127.0.0.1', destination: '127.0.0.1' })
  assert.equal(enrolled.status, 201, JSON.stringify(enrolled))
  const redeemedGrant = await call(`/api/collections/controller_enrollment_grants/records/${grant.json.id}`, 'GET', undefined, superToken)
  assert.equal(redeemedGrant.status, 200, JSON.stringify(redeemedGrant))
  assert.equal(redeemedGrant.json.operator_id, user.json.id)
  assert.equal(redeemedGrant.json.redeemed_device, enrolled.json.deviceId)
  const ownedGrantList = await call(`/api/collections/controller_enrollment_grants/records?filter=${encodeURIComponent(`operator_id = "${user.json.id}"`)}`, 'GET', undefined, superToken)
  assert.equal(ownedGrantList.status, 200, JSON.stringify(ownedGrantList))
  assert.ok(ownedGrantList.json.items.some((item) => item.redeemed_device === enrolled.json.deviceId))
  assert.equal(ownedGrantList.json.items.find((item) => item.redeemed_device === enrolled.json.deviceId).operator_id, user.json.id)
  const grantStatusPending = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusPending.status, 200, JSON.stringify(grantStatusPending))
  assert.equal(grantStatusPending.json.state, 'pending', JSON.stringify(grantStatusPending))
  const replay = await call('/api/karaoke/controllers/enroll', 'POST', { token: grant.json.token, deviceName: 'replay' })
  assert.equal(replay.status, 410)
  assert.equal(replay.json.error, 'enrollment_grant_replayed')
  assert.doesNotMatch(JSON.stringify(replay.json), new RegExp(grant.json.token))

  const manualGrant = await call('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: '127.0.0.1', destination: '127.0.0.1' }, tabletToken)
  assert.equal(manualGrant.status, 201)
  const groupedShortCode = manualGrant.json.shortCode.match(/.{4}/g).join('-').toLowerCase()
  const manualEnroll = await call('/api/karaoke/controllers/enroll', 'POST', {
    shortCode: `  ${groupedShortCode}  `,
    deviceName: 'manual tablet',
    serverHost: '127.0.0.1',
    destination: ' 127.0.0.1 ',
  })
  assert.equal(manualEnroll.status, 201, JSON.stringify(manualEnroll))
  assert.doesNotMatch(JSON.stringify(manualEnroll), new RegExp(manualGrant.json.shortCode))

  const otherUser = await call('/api/collections/users/records', 'POST', { email: 'other-tablet@example.test', password: 'TabletPassword123!', passwordConfirm: 'TabletPassword123!', role: 'tablet_admin' }, superToken)
  assert.equal(otherUser.status, 200, JSON.stringify(otherUser))
  const otherAuth = await call('/api/collections/users/auth-with-password', 'POST', { identity: 'other-tablet@example.test', password: 'TabletPassword123!' })
  assert.equal(otherAuth.status, 200, JSON.stringify(otherAuth))
  const otherGrant = await call('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: '127.0.0.1', destination: '127.0.0.1' }, otherAuth.json.token)
  assert.equal(otherGrant.status, 201, JSON.stringify(otherGrant))
  const otherEnroll = await call('/api/karaoke/controllers/enroll', 'POST', { token: otherGrant.json.token, deviceName: 'other operator tablet', serverHost: '127.0.0.1', destination: '127.0.0.1' })
  assert.equal(otherEnroll.status, 201, JSON.stringify(otherEnroll))
  const otherDeviceAuth = await call('/api/collections/controller_devices/auth-with-password', 'POST', { identity: otherEnroll.json.deviceKey, password: otherEnroll.json.deviceSecret })
  assert.equal(otherDeviceAuth.status, 200, JSON.stringify(otherDeviceAuth))
  const otherDeviceToken = otherDeviceAuth.json.token
  const otherSession = await call('/api/karaoke/controllers/sessions', 'POST', {}, otherDeviceToken)
  assert.equal(otherSession.status, 201, JSON.stringify(otherSession))
  assert.equal((await call('/api/karaoke/controllers/state', 'PUT', { sessionId: otherSession.json.id, generation: otherSession.json.generation, connectionState: 'connected', videoId: 'dQw4w9WgXcQ', playerState: 'paused', positionSeconds: 0, durationSeconds: 10, lastCommandSequence: 0 }, otherDeviceToken)).status, 200)

  const expiredGrant = await call('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: '127.0.0.1', destination: '127.0.0.1' }, tabletToken)
  assert.equal(expiredGrant.status, 201)
  assert.equal((await call(`/api/collections/controller_enrollment_grants/records/${expiredGrant.json.id}`, 'PATCH', { expires_at: new Date(Date.now() - 1000).toISOString() }, superToken)).status, 200)
  const expiredEnroll = await call('/api/karaoke/controllers/enroll', 'POST', { token: expiredGrant.json.token, deviceName: 'expired tablet', serverHost: '127.0.0.1', destination: '127.0.0.1' })
  assert.equal(expiredEnroll.status, 410)
  assert.equal(expiredEnroll.json.error, 'enrollment_grant_expired')
  assert.doesNotMatch(JSON.stringify(expiredEnroll.json), new RegExp(expiredGrant.json.token))

  const revokedGrant = await call('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: '127.0.0.1', destination: '127.0.0.1' }, tabletToken)
  assert.equal(revokedGrant.status, 201)
  const revoked = await call(`/api/karaoke/controllers/enrollment-grants/${revokedGrant.json.id}/revoke`, 'POST', {}, tabletToken)
  assert.equal(revoked.status, 200, JSON.stringify(revoked))
  assert.equal(revoked.json.status, 'revoked')
  const revokedEnroll = await call('/api/karaoke/controllers/enroll', 'POST', { token: revokedGrant.json.token, deviceName: 'revoked tablet', serverHost: '127.0.0.1', destination: '127.0.0.1' })
  assert.equal(revokedEnroll.status, 410)
  assert.equal(revokedEnroll.json.error, 'enrollment_grant_revoked')
  assert.doesNotMatch(JSON.stringify(revokedEnroll.json), new RegExp(revokedGrant.json.token))

  const deviceAuth = await call('/api/collections/controller_devices/auth-with-password', 'POST', { identity: enrolled.json.deviceKey, password: enrolled.json.deviceSecret })
  assert.equal(deviceAuth.status, 200)
  const deviceToken = deviceAuth.json.token
  const session = await call('/api/karaoke/controllers/sessions', 'POST', {}, deviceToken)
  assert.equal(session.status, 201)
  const grantStatusSession = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusSession.status, 200, JSON.stringify(grantStatusSession))
  assert.equal(grantStatusSession.json.state, 'pending', JSON.stringify(grantStatusSession))
  const resumed = await call('/api/karaoke/controllers/sessions', 'POST', { resumeSessionId: session.json.id }, deviceToken)
  assert.deepEqual([resumed.status, resumed.json.id, resumed.json.generation], [201, session.json.id, session.json.generation])
  const commandBody = { deviceId: enrolled.json.deviceId, action: 'open_video', payload: { videoId: 'dQw4w9WgXcQ' }, idempotencyKey: 'integration-open-001' }
  const command = await call('/api/karaoke/controller-commands', 'POST', commandBody, tabletToken)
  assert.equal(command.status, 201)
  assert.equal(command.json.videoId, commandBody.payload.videoId)
  assert.equal((await call('/api/karaoke/controller-commands', 'POST', commandBody, tabletToken)).status, 200)
  assert.equal((await call('/api/karaoke/controller-commands', 'POST', { ...commandBody, action: 'pause', payload: {} }, tabletToken)).status, 409)
  assert.equal((await call('/api/karaoke/controller-commands', 'POST', commandBody, deviceToken)).status, 403)
  assert.ok([400, 403].includes((await call('/api/collections/controller_commands/records', 'POST', { device: enrolled.json.deviceId }, deviceToken)).status))
  const query = `/api/karaoke/controllers/commands?sessionId=${session.json.id}&generation=${session.json.generation}&after=999`
  const fetched = await call(query, 'GET', undefined, deviceToken)
  assert.equal(fetched.status, 200, JSON.stringify(fetched))
  assert.equal(fetched.json.commands[0].id, command.json.id)
  assert.equal(fetched.json.commands[0].videoId, commandBody.payload.videoId)
  const seekBody = { deviceId: enrolled.json.deviceId, action: 'seek', payload: { seekSeconds: 30 }, idempotencyKey: 'integration-seek-001' }
  const seekCommand = await call('/api/karaoke/controller-commands', 'POST', seekBody, tabletToken)
  assert.equal(seekCommand.status, 201)
  assert.equal(seekCommand.json.seekSeconds, seekBody.payload.seekSeconds)
  const fetchedWithSeek = await call(query, 'GET', undefined, deviceToken)
  assert.equal(fetchedWithSeek.status, 200, JSON.stringify(fetchedWithSeek))
  assert.equal(fetchedWithSeek.json.commands.find((item) => item.id === seekCommand.json.id)?.seekSeconds, seekBody.payload.seekSeconds)
  const streamAbort = new AbortController()
  const stream = await fetch(`${base}/api/realtime`, { headers: { authorization: `Bearer ${deviceToken}` }, signal: streamAbort.signal })
  assert.equal(stream.status, 200)
  const reader = stream.body.getReader()
  let sseText = ''
  for (let i = 0; i < 10 && !sseText.includes('PB_CONNECT'); i++) {
    const chunk = await Promise.race([reader.read(), new Promise((resolve) => setTimeout(() => resolve({ done: true }), 500))])
    if (chunk.done) break
    sseText += new TextDecoder().decode(chunk.value)
  }
  const clientId = /"clientId"\s*:\s*"([^"]+)"/.exec(sseText)?.[1]
  assert.ok(clientId, `missing PB_CONNECT in SSE: ${sseText}`)
  const subscription = await call('/api/realtime', 'POST', { clientId, subscriptions: ['controller_commands/*'] }, deviceToken)
  assert.ok([200, 204].includes(subscription.status), JSON.stringify(subscription))
  const sseCommand = await call('/api/karaoke/controller-commands', 'POST', { ...commandBody, idempotencyKey: 'integration-sse-001' }, tabletToken)
  assert.equal(sseCommand.status, 201)
  const createEvent = await readSseRecord((data) => data.action === 'create' && data.record?.id === sseCommand.json.id, reader)
  assert.equal(createEvent.record.id, sseCommand.json.id)
  const sseFetch = await call(query, 'GET', undefined, deviceToken)
  assert.equal(sseFetch.status, 200)
  assert.ok(sseFetch.json.commands.some((item) => item.id === sseCommand.json.id))
  const sseAckBody = { sessionId: session.json.id, generation: session.json.generation, status: 'succeeded' }
  assert.equal((await call(`/api/karaoke/controllers/commands/${sseCommand.json.id}/ack`, 'POST', sseAckBody, deviceToken)).status, 200)
  const updateEvent = await readSseRecord((data) => data.action === 'update' && data.record?.id === sseCommand.json.id, reader)
  assert.equal(updateEvent.record.id, sseCommand.json.id)
  streamAbort.abort()
  const ackBody = { sessionId: session.json.id, generation: session.json.generation, status: 'succeeded' }
  const ack = await call(`/api/karaoke/controllers/commands/${command.json.id}/ack`, 'POST', ackBody, deviceToken)
  assert.equal(ack.status, 200, JSON.stringify(ack))
  assert.equal((await call(`/api/karaoke/controllers/commands/${command.json.id}/ack`, 'POST', ackBody, deviceToken)).status, 200)
  assert.equal((await call(`/api/karaoke/controllers/commands/${command.json.id}/ack`, 'POST', { ...ackBody, status: 'failed' }, deviceToken)).status, 409)
  const raceCommand = await call('/api/karaoke/controller-commands', 'POST', { ...commandBody, idempotencyKey: 'integration-race-001' }, tabletToken)
  assert.equal(raceCommand.status, 201)
  const raceAcks = await Promise.all(['succeeded', 'failed'].map((status) => call(`/api/karaoke/controllers/commands/${raceCommand.json.id}/ack`, 'POST', { ...ackBody, status }, deviceToken)))
  assert.deepEqual(raceAcks.map((response) => response.status).sort(), [200, 409])
  const state = { sessionId: session.json.id, generation: session.json.generation, connectionState: 'connected', videoId: 'dQw4w9WgXcQ', playerState: 'playing', positionSeconds: 1.25, durationSeconds: 10, lastCommandSequence: 1 }
  const stateResponse = await call('/api/karaoke/controllers/state', 'PUT', state, deviceToken)
  assert.equal(stateResponse.status, 200, JSON.stringify(stateResponse))
  const grantStatusConnected = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusConnected.status, 200, JSON.stringify(grantStatusConnected))
  assert.equal(grantStatusConnected.json.state, 'connected', JSON.stringify(grantStatusConnected))
  assert.equal(grantStatusConnected.json.connectionState, 'connected')
  assert.equal(grantStatusConnected.json.stateGeneration, session.json.generation)
  assert.equal(grantStatusConnected.json.sessionActive, true)
  assert.equal(Object.prototype.hasOwnProperty.call(grantStatusConnected.json, 'session'), false)
  assert.equal(Object.prototype.hasOwnProperty.call(grantStatusConnected.json, 'sessionId'), false)

  const party = await call('/api/karaoke/parties', 'POST', {}, tabletToken)
  assert.equal(party.status, 201, JSON.stringify(party))
  const initialPartyStatus = await call(`/api/karaoke/tablet/status?partyId=${party.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(initialPartyStatus.status, 200, JSON.stringify(initialPartyStatus))
  // Multiple owned live controllers must never be guessed; targeted binding is authoritative.
  assert.equal(initialPartyStatus.json.controller.device, null)
  const crossOperatorBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: otherEnroll.json.deviceId }, tabletToken)
  assert.equal(crossOperatorBind.status, 409, JSON.stringify(crossOperatorBind))
  assert.equal(crossOperatorBind.json.error, 'controller_target_not_owned')
  assert.equal((await call(`/api/karaoke/tablet/status?partyId=${party.json.id}`, 'GET', undefined, tabletToken)).json.controller.device, null)
  const firstExplicitBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: enrolled.json.deviceId }, tabletToken)
  assert.equal(firstExplicitBind.status, 200, JSON.stringify(firstExplicitBind))
  assert.equal((await call(`/api/karaoke/tablet/status?partyId=${party.json.id}`, 'GET', undefined, tabletToken)).json.controller.device.id, enrolled.json.deviceId)
  const manualDeviceAuth = await call('/api/collections/controller_devices/auth-with-password', 'POST', { identity: manualEnroll.json.deviceKey, password: manualEnroll.json.deviceSecret })
  assert.equal(manualDeviceAuth.status, 200, JSON.stringify(manualDeviceAuth))
  const manualDeviceToken = manualDeviceAuth.json.token
  const manualSession = await call('/api/karaoke/controllers/sessions', 'POST', {}, manualDeviceToken)
  assert.equal(manualSession.status, 201, JSON.stringify(manualSession))
  const manualState = await call('/api/karaoke/controllers/state', 'PUT', { sessionId: manualSession.json.id, generation: manualSession.json.generation, connectionState: 'connected', videoId: 'dQw4w9WgXcQ', playerState: 'paused', positionSeconds: 0, durationSeconds: 10, lastCommandSequence: 0 }, manualDeviceToken)
  assert.equal(manualState.status, 200, JSON.stringify(manualState))
  const missingBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: 'missing-device' }, tabletToken)
  assert.equal(missingBind.status, 404, JSON.stringify(missingBind))
  const explicitBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: manualEnroll.json.deviceId }, tabletToken)
  assert.equal(explicitBind.status, 200, JSON.stringify(explicitBind))
  const partyStatus = await call(`/api/karaoke/tablet/status?partyId=${party.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(partyStatus.status, 200, JSON.stringify(partyStatus))
  assert.equal(partyStatus.json.controller.device.id, manualEnroll.json.deviceId)
  const manualStateRecords = await call(`/api/collections/controller_state/records?filter=${encodeURIComponent(`device = "${manualEnroll.json.deviceId}"`)}`, 'GET', undefined, superToken)
  assert.equal(manualStateRecords.status, 200, JSON.stringify(manualStateRecords))
  assert.equal((await call(`/api/collections/controller_state/records/${manualStateRecords.json.items[0].id}`, 'PATCH', { observed_at: new Date(Date.now() - 91 * 1000).toISOString() }, superToken)).status, 200)
  const staleBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: manualEnroll.json.deviceId }, tabletToken)
  assert.equal(staleBind.status, 409, JSON.stringify(staleBind))
  assert.equal((await call(`/api/karaoke/tablet/status?partyId=${party.json.id}`, 'GET', undefined, tabletToken)).json.controller.device.id, manualEnroll.json.deviceId)
  assert.equal((await call('/api/karaoke/controllers/state', 'PUT', { sessionId: manualSession.json.id, generation: manualSession.json.generation, connectionState: 'connected', videoId: 'dQw4w9WgXcQ', playerState: 'paused', positionSeconds: 0, durationSeconds: 10, lastCommandSequence: 0 }, manualDeviceToken)).status, 200)
  const legacyBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id }, tabletToken)
  assert.equal(legacyBind.status, 200, JSON.stringify(legacyBind))
  assert.equal((await call(`/api/collections/controller_devices/records/${manualEnroll.json.deviceId}`, 'PATCH', { revoked: true }, superToken)).status, 200)
  const revokedTargetBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: manualEnroll.json.deviceId }, tabletToken)
  assert.equal(revokedTargetBind.status, 409, JSON.stringify(revokedTargetBind))
  const raceGrant = await call('/api/karaoke/controllers/enrollment-grants', 'POST', { expectedServerHost: '127.0.0.1', destination: '127.0.0.1' }, tabletToken)
  assert.equal(raceGrant.status, 201)
  const redemptionRace = await Promise.all([1, 2].map((index) => call('/api/karaoke/controllers/enroll', 'POST', { token: raceGrant.json.token, deviceName: `race-${index}`, serverHost: '127.0.0.1', destination: '127.0.0.1' })))
  assert.deepEqual(redemptionRace.map((response) => response.status).sort(), [201, 410])
  assert.equal(redemptionRace.find((response) => response.status === 410).json.error, 'enrollment_grant_replayed')
  const stateRecords = await call(`/api/collections/controller_state/records?filter=${encodeURIComponent(`device = "${enrolled.json.deviceId}"`)}`, 'GET', undefined, superToken)
  assert.equal(stateRecords.status, 200, JSON.stringify(stateRecords))
  assert.equal(stateRecords.json.items.length, 1)
  assert.equal((await call(`/api/collections/controller_state/records/${stateRecords.json.items[0].id}`, 'PATCH', { observed_at: new Date(Date.now() - 90 * 1000 - 1).toISOString() }, superToken)).status, 200)
  const grantStatusStale = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusStale.status, 200, JSON.stringify(grantStatusStale))
  assert.equal(grantStatusStale.json.state, 'pending', JSON.stringify(grantStatusStale))
  assert.equal((await call('/api/karaoke/controllers/state', 'PUT', state, deviceToken)).status, 200)
  const next = await call('/api/karaoke/controllers/sessions', 'POST', {}, deviceToken)
  assert.equal(next.json.generation, session.json.generation + 1)
  const grantStatusOldGeneration = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusOldGeneration.status, 200, JSON.stringify(grantStatusOldGeneration))
  assert.equal(grantStatusOldGeneration.json.state, 'pending', JSON.stringify(grantStatusOldGeneration))
  assert.equal((await call(query, 'GET', undefined, deviceToken)).status, 409)
  assert.equal((await call('/api/karaoke/controllers/state', 'PUT', state, deviceToken)).status, 409)
  assert.equal((await call(`/api/karaoke/controllers/commands/${command.json.id}/ack`, 'POST', ackBody, deviceToken)).status, 409)

  assert.equal((await call(`/api/collections/controller_sessions/records/${next.json.id}`, 'PATCH', { expires_at: new Date(Date.now() - 1000).toISOString() }, superToken)).status, 200)
  const grantStatusExpiredSession = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusExpiredSession.status, 200, JSON.stringify(grantStatusExpiredSession))
  assert.equal(grantStatusExpiredSession.json.state, 'pending', JSON.stringify(grantStatusExpiredSession))
  assert.equal((await call(`/api/collections/controller_devices/records/${enrolled.json.deviceId}`, 'PATCH', { revoked: true }, superToken)).status, 200)
  const grantStatusRevokedDevice = await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, tabletToken)
  assert.equal(grantStatusRevokedDevice.status, 200, JSON.stringify(grantStatusRevokedDevice))
  assert.equal(grantStatusRevokedDevice.json.state, 'revoked', JSON.stringify(grantStatusRevokedDevice))

  assert.equal((await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}`, 'GET', undefined, otherAuth.json.token)).status, 404)
  assert.equal((await call(`/api/karaoke/controllers/enrollment-grants/${grant.json.id}/revoke`, 'POST', {}, otherAuth.json.token)).status, 404)
  assert.equal((await call(`/api/collections/karaoke_parties/records/${party.json.id}`, 'PATCH', { expires_at: new Date(Date.now() - 1000).toISOString() }, superToken)).status, 200)
  const expiredPartyBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: manualEnroll.json.deviceId }, tabletToken)
  assert.equal(expiredPartyBind.status, 410, JSON.stringify(expiredPartyBind))
  const wrongOperatorBind = await call('/api/karaoke/tablet/controller/bind', 'POST', { partyId: party.json.id, deviceId: manualEnroll.json.deviceId }, otherAuth.json.token)
  assert.equal(wrongOperatorBind.status, 404, JSON.stringify(wrongOperatorBind))
})
