const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

test('legacy playlist scope is durable, tablet constrained, and cron driven', () => {
  const hook = fs.readFileSync(__dirname + '/../pb_hooks/party_queue.pb.js', 'utf8')
  const migration = fs.readFileSync(__dirname + '/../pb_migrations/1784600060_operator_assumed_legacy_playlist.js', 'utf8')
  assert.match(hook, /PL8D4Iby0Bmm94U_rwuJuocyC1xFoPTd5R/)
  assert.match(hook, /operator_assumed_legacy_playlist/)
  assert.match(hook, /cronAdd\('legacy-playlist-reconcile'/)
  assert.match(hook, /q\.query\(c, 'wake'\)/)
  assert.match(hook, /legacy-playlist-cron-v1/)
  assert.match(hook, /legacyPolicyVersion: 'mb-majority-v2'/)
  assert.match(hook, /policy_version = \{:policy\}/)
  assert.match(hook, /candidateRecordingIds/)
  assert.match(hook, /musicBrainzRequests/)
  assert.match(hook, /lease_expires_at/)
  assert.match(hook, /musicbrainz-identity\.cjs/)
  assert.match(hook, /MB_ROOT/)
  assert.match(hook, /cache_key/)
  assert.match(hook, /sleep\(1000\)/)
  assert.match(hook, /legacyScopeRows/)
  assert.match(hook, /binding_row_digest/)
  assert.match(hook, /initiated_by/)
  assert.match(hook, /input_drift/)
  assert.doesNotMatch(hook, /binding_rows_json/)
  assert.match(hook, /const cache = cached \|\| new Record/)
  assert.match(hook, /legacySaveJob\(q, job, token/)
  assert.match(hook, /reportCount/)
  assert.match(hook, /updatedAt/)
  assert.match(hook, /auditTail/)
  assert.match(hook, /catalog\/\{id\}\/audit/)
  assert.match(hook, /lease_token'.*!== token/)
  assert.doesNotMatch(hook, /row\.title \|\| ''\).*row\.artist/)
  assert.match(migration, /binding_input_digest/)
  assert.match(migration, /karaoke_legacy_playlist_jobs/)
})
